### ISSUE TITLE
Allow for orientation settings (Landscape/Portrait)

### ISSUE THREAD

**Issue by shyzus** [shyzus/gnome-shell-extension-screen-autorotate#11]
**Is your feature request related to a problem? Please describe.**
The extension works perfectly on my notebook.

I only have a problem with a small device where the default orientation is portrait (rotated to the right). Unfortunately, the invert function can not compensate for this and so the image remains in landscape format as portrait.

**Describe the solution you'd like**
It would be great if you could also set a default orientation.
If you set the default orientation in the display settings, it will be overwritten and set incorrectly again when you rotate the image.

**Describe alternatives you've considered**
N/A

**Additional context**
Full error report from extensions.gnome.org:

> The extension works perfectly on my notebook.
>
> I only have a problem with a small device where the default orientation is portrait (rotated to the right). Unfortunately, the invert function can not compensate for this and so the image remains in landscape format as portrait.
>
> It would be great if you could also set a default orientation.
> If you set the default orientation in the display settings, it will be overwritten and set incorrectly again when you rotate the image.
>
> Thanks!
>
> Best regards
> Joe

**Comment by JoeMeissl** [comment]
Hello,

I have tested the fix.

The screen orientation works, but in landscape mode the image is now mirrored.
Interestingly, when I take a screenshot on the notebook, the image is correct. Therefore, I took a photo with the smartphone to be able to show the error.

Kind regards
Joe

![IMG_20230314_174745](https://user-images.githubusercontent.com/70130483/225109655-0f0fcb48-c497-45c9-9db2-7f487b8a11d3.jpg)

**Comment by shyzus** [comment]
I have been trying to see how a mirrored state could be achieved with the existing code for calculating the orientation. I do not see a scenario where that can happen. However I do think this can be resolved trough other means outside of the extensions. A different issue namely #7 .

The issue here was the orientation of the stylus pointer. The thing that is potentially relevant for you is [this post](https://github.com/shyzus/gnome-shell-extension-screen-autorotate/issues/7#issuecomment-1358841806) in that issue. 

Could you try seeing if these steps could help resolve your issue? I think that the kernel parameter alone probably would fix this. but some trial and error is needed.

**Comment by shyzus** [comment]
I see il be researching this problem and try and find a way to reproduce it on my end resolve it.

**Comment by BlackDuck888** [comment]
Hey,
 I tried to mod your extension for the same reason (portrait mode display) an ran into the same problem. The Solution is easy and looks like that.

Change https://github.com/shyzus/gnome-shell-extension-screen-autorotate/blob/main/screen-rotate%40shyzus.github.io/extension.js#L193

from 

```
const sensor_output = Orientation[orientation];
```
to
```
let offset = 1;
const sensor_output = (Orientation[orientation] + offset) % 4;
```

And if I could also make a wish :) at the same time it would be fantastic if i could activate 

`gsettings set org.gnome.desktop.a11y.applications screen-keyboard-enabled`

on all non default rotations. Or better if this would be configurable for each direction.

**Comment by shyzus** [comment]
@BlackDuck888 I have tried out your changes and I can't see any changes in my setup. Which I suppose is a good thing considering you report that this change does fix your issue with the mirrored display output?

Please confirm if you have tried it out and it resolves this issue. Il merge this solution in when there is confirmation.

Regarding the gsettings. That is an interesting addition to the extension. Il make a seperate issue for it considering it doesn't really fall under this issue.

Thank you very much for your time and efforts! :+1:

**Comment by BlackDuck888** [comment]
@shyzus I can confirm that I am successfully running my GPD Pocket3 with this change. Because this device also has a portrait display horizontally installed.

Your approach in https://github.com/shyzus/gnome-shell-extension-screen-autorotate/blob/11-allow-for-orientation-settings-landscapeportrait/screen-rotate%40shyzus.github.io/extension.js#L200 can lead to a sensor output of 4 and 4 is the mirrored one. Normal are the values 0-3. The modulo of 4 leads to the fact that it starts after 3 again at 0.

If the fix is to work for all types of twisted displays, an offset of 1, 2 or 3 must be possible to select.
