### ISSUE TITLE
Ability to rotate screen without accelerometer

### ISSUE THREAD

**Issue by shyzus** [shyzus/gnome-shell-extension-screen-autorotate#12]
**Is your feature request related to a problem? Please describe.**
I have an HP landscape/portrait rotatable desktop monitor, which obviously has to be rotated manually. I can do that in the Display settings, but it's a pain to have to dig in there. so I was looking for an extension that would let me toggle that setting right from the user menu. This extension won't help me, which is fine, but from the description it *sounded like* it could. 

**Describe the solution you'd like**
A way to rotate the screen from the quick settings menu.

**Describe alternatives you've considered**
N/A

**Additional context**
Full review from extensions.gnome.org:

>Ferdnyc:
>
> The extension seems great, and thanks for keeping it alive. My only suggestion would be to add something in the description about needing... (well, either iio-sensor-proxy, or an accelerometer, or some sort of hardware support for detecting rotation. However you want to explain it.)
>
> Reasoning: I have an HP landscape/portrait rotatable desktop monitor, which obviously has to be rotated manually. I can do that in the Display settings, but it's a pain to have to dig in there so I was looking for an extension that would let me toggle that setting right from the user menu. This extension won't help me, which is fine, but from the description it *sounded like* it could.
>
> (Yes, I know it says it's forked from Screen Autorotate, but that's the point: The name change gave the impression that maybe it wasn't just for autorotation. Nope, turns out the old name is more accurate.)

**Comment by theotheroracle** [comment]
this will be very useful on my gnome-mobile phone !

**Comment by shyzus** [comment]
@theotheroracle I believe the code in this branch is ready for testing. I have already tested this on my own desktop and laptop that has no accelerometer. 

Both desktop and laptop showed the expected result of being able to use a quick toggle to flip between landscape and portrait orientation.

Could you test this branch on your gnome-mobile phone?

You can use the below instructions to do so:

**Before executing the following make sure to remove the extension first**

```
git clone -b 12-ability-to-rotate-screen-without-accelerometer https://github.com/shyzus/gnome-shell-extension-screen-autorotate.git
cd gnome-shell-extension-screen-autorotate
cp -r screen-rotate@shyzus.github.io ~/.local/share/gnome-shell/extensions
```

**Comment by Friedjof** [comment]
I would also be very interested in this Featcher because I can't manage to rotate my screen by only 90deg.
I can only do 0 and 180deg. Or can you tell me what the problem might be?

When testing it, I realised that it is unfortunately not compatible with my Gnome version. Are you still working on it?

![grafik](https://github.com/shyzus/gnome-shell-extension-screen-autorotate/assets/60787233/8c709ae3-738a-4423-8e4f-91888d5634f8)

**Comment by Friedjof** [comment]
I can set it up the way I want with this setting. But I haven't found any real documentation on what value triggers what. Also, the change is only applied the next time I rotate the screen. Is there any other way to do this?

![grafik](https://github.com/shyzus/gnome-shell-extension-screen-autorotate/assets/60787233/ad71131a-a798-47b8-88e4-33e2872653e2)

**Comment by shyzus** [comment]
> I would also be very interested in this Featcher because I can't manage to rotate my screen by only 90deg. I can only do 0 and 180deg. Or can you tell me what the problem might be?
> 
> When testing it, I realised that it is unfortunately not compatible with my Gnome version. Are you still working on it?
> 
> ![grafik](https://private-user-images.githubusercontent.com/60787233/303798251-8c709ae3-738a-4423-8e4f-91888d5634f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1MzE3NDcsIm5iZiI6MTcwNzUzMTQ0NywicGF0aCI6Ii82MDc4NzIzMy8zMDM3OTgyNTEtOGM3MDlhZTMtNzM4YS00NDIzLThlNGYtOTE4ODhkNTYzNGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDAyMTcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2MTY1YmFhNzVjYWMwOGE2NWY4ZmM2NDg2ZmYzOTUxNmRiNTFmMzE5OGRmYTJlZjFmMzNjOWE0MzAzOGFjODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8PiJEdW-jzbass_gmA5Ew-uFpo8MuJ5RBe8sCtHUQqo)

Thanks for trying it out! At the moment the default behaviour is to switch between landscape and portrait which will always be a 180deg difference. This is the default behaviour as this extension may also be used on GNOME mobile devices where its preferable to just have one quick toggle rather than something more complex.

I was doubtful it needed more options, but considering your feedback. I will add an option in the preferences page to enable a QuickToggle menu which gives you all four options of: Landscape, Landscape Inverted, Portrait, Portrait inverted.

In regards to the GNOME version. As of the release of v13 of this extension, only GNOME 45 and upwards is supported. This feature may end up being backported to older versions of this extension that support GNOME 41 up to GNOME 45.

**Comment by shyzus** [comment]
> I can set it up the way I want with this setting. But I haven't found any real documentation on what value triggers what. Also, the change is only applied the next time I rotate the screen. Is there any other way to do this?
> 
> ![grafik](https://private-user-images.githubusercontent.com/60787233/303799222-ad71131a-a798-47b8-88e4-33e2872653e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1MzE3NDcsIm5iZiI6MTcwNzUzMTQ0NywicGF0aCI6Ii82MDc4NzIzMy8zMDM3OTkyMjItYWQ3MTEzMWEtYTc5OC00N2I4LTg4ZTQtMzNlMjg3MjY1M2UyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDAyMTcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1M2E1MDJkNjRiZTBjNWFkN2E2NmE1M2YzNGYzZTFiMTc0NTk1NDMxNDljZGUxNWQ0ZjY2MWRiOTZjNWYzNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KHuumDGLn_TGmebZLTTk6EGRAt9wBe1gpR_FToIuPpE)

There isn't any documentation aside from the comments in the code for the orientation offset. I will be working on a wiki entry/page with documentation in the future.

Using the following image as a crude representation of a display:

![image](https://github.com/shyzus/gnome-shell-extension-screen-autorotate/assets/12612358/a8920b64-a6bb-4686-91f3-4c28dea2150b)

The orientation offset, offsets the calculated orientation value. The orientation value is determined by the value for each state of the display orientation which in total are 4.

- 0 = normal orientation (0/360deg)
- 1 = left side of the display is facing up (-90deg)
- 2 = bottom side of the display is facing up (upside down) (-180/180deg)
- 3 = right side of the display is facing up (90deg)

For example:
Your orientation value is 0 and your offset is set to 1. The [calculation](https://github.com/shyzus/gnome-shell-extension-screen-autorotate/blob/267304a9aaf9e684a2d9ac38acbea56895cdf041/screen-rotate%40shyzus.github.io/extension.js#L223) is: (orientation + offset) % 4.

Additionally judging from the preference page screenshot you have an older version than latest(v15). In v15 the range for offset was changed from -3 <-> 3 to 0 <-> 3.

Thank you for posting your feedback. Feel free to check onto this issue to see any progress.
