### ISSUE TITLE
Support for Gnome 44.0

### ISSUE THREAD

**Issue by efosmark** [shyzus/gnome-shell-extension-screen-autorotate#13]
Last night I updated to Gnome `44.0 (beta)` and now `44.0 (rc)`. I tried screen-autorotate and so far everything looks to be working as expected. Checking the logs, I'm not seeing anything from this extension.

I think all that's needed is to update the `shell-version` to include `44`.

**Comment by shyzus** [comment]
Thanks for testing this @efosmark I will try to have the shell version updated before Gnome 44 is officially released.
