### ISSUE TITLE
On-Screen Keyboard preferences

### ISSUE THREAD

**Issue by shyzus** [shyzus/gnome-shell-extension-screen-autorotate#15]
**Is your feature request related to a problem? Please describe.**
Suggested feature by @BlackDuck888 in https://github.com/shyzus/gnome-shell-extension-screen-autorotate/issues/11#issuecomment-1629140418 . I find this suggestion to be a useful addition to this extension as I have encountered flaky/unreliable on-screen keyboard behaviour.

**Describe the solution you'd like**
I want to be able to toggle which orientation the on-screen keyboard is enabled and options to have it enabled for all orientations or suppressed for all orientations.

I think the best way to implement this would be trough the preferences of the extensions. Adding checkboxes or radio buttons for each possible orientation. Such as:

- [ ] Normal
- [ ] Left-Up
- [ ] Bottom-Up
- [ ] Right-Up

A toggled state would translate to wanting the on-screen keyboard to be enabled when those orientations are detected.

**Describe alternatives you've considered**
Using Gsettings manually or other extensions that claim to be resolving this issue by providing a different on-screen keyboard provider than the built-in one.

**Comment by shyzus** [comment]
@BlackDuck888 Thank you for testing it out. I am glad you like it. I will be merging this into main and hopefully it will pass trough E.G.O in one go and il make a release for it. 

Regarding the AUR. I am not the maintainer for that package. If you are using it make sure to check the PKGBUILD to verify nothing nefarious is going on.

**Comment by BlackDuck888** [comment]
Last versions came to AUR so I will just wait.
