### ISSUE TITLE
Bug: Rotation is not working correct.

### ISSUE THREAD

**Issue by BlackDuck888** [shyzus/gnome-shell-extension-screen-autorotate#17]
@shyzus 

The Main branch does not look correct for me and it is not working correct.

Why did you make "+ 1" here ?
https://github.com/shyzus/gnome-shell-extension-screen-autorotate/blob/5e6dfaa36af538c2fda422899a9a2045bce63334/screen-rotate%40shyzus.github.io/extension.js#L206

If the sensor_output is already 3 you would make ist for 4 which will end in a mirrored display. 

How could a sensor in position 4 here https://github.com/shyzus/gnome-shell-extension-screen-autorotate/blob/main/screen-rotate%40shyzus.github.io/extension.js#L216? 

In L213 you check that the sensor is horizontal and the reverse_vertical_direction is in that block. I am not sure if this bring the expected result. 

I will try some debugging and extended tests on my system and came back to this issue.

My base idea was by changing `const sensor_output = (Orientation[orientation] + offset) % 4;` that sensor "think" he is in a normal position, and a portrait display behaves like a normal one.

**Comment by shyzus** [comment]
Just to verify did you use the toggle in the preferences of the extension?

If I recall correctly, the line on 206 was already present on the branch before your suggested code. it was done to enable the extra 2 orientation flip toggles.

Please verify if its not working properly while the toggle: `Mirrored Portrait Display (ex: GPD Pocket 3)` is enable. @BlackDuck888

**Comment by BlackDuck888** [comment]
@shibacomputer I am quite sure if you are using the GPD Pocket 3 too, like me, that you have the same problem. I am currently reworking this add-in to create a pull request to fix all problems. 

The rotation is already working correct for me. Now i clean the settings menu with correct option and settings. And i plan to add to activate the onscreen keyboard in a rotated state. 

The main problem of the GDP Pocket is the missing tablet sensor, if this would there mutter/wayland should do it correct. I tried this by patching mutter, but i have no fun to do this on every update.

**Comment by BlackDuck888** [comment]
Sounds like a plan! Next week i am on holiday and have much more time for this.  Meanwile i rebase my work to  branch(17-bug-rotation-is-not-working-correct)

**Comment by shyzus** [comment]
@BlackDuck888 with pull request #19 being merged into main I have rebased the branch(17-bug-rotation-is-not-working-correct) for this issue onto main. 

Please be sure to pull any new changes before continuing to prevent merge conflicts. 

The changes in #19 should make debugging/troubleshooting less time consuming as well. 
I look forward to your response.

**Comment by shyzus** [comment]
To prevent this issue from going stale and to inform of you of the changes made to the main branch. 

@BlackDuck888 I will rebase the branch (17-bug-rotation-is-not-working-correct) onto main. So that whatever testing/development you do on that branch won't result into merge conflicts.
