### ISSUE TITLE
Extension failed on GNOME Shell 45

### ISSUE THREAD

**Issue by luyatshimbalanga** [shyzus/gnome-shell-extension-screen-autorotate#20]
**Describe the bug**
Screen Autorotate failed when enabling it on GNOME Shell 45

**To Reproduce**
1. Install either from both GNOME Extensions or Fedora repository
2. Switch the extension to ON

**Expected behavior**
Screen Autorotate should work as intended

**Screenshots**
![image](https://github.com/shyzus/gnome-shell-extension-screen-autorotate/assets/7230131/89bdcff0-8672-4602-b4d9-26e43d79f0e6)

**Desktop (please complete the following information):**
 - OS: Fedora Linux 39 Design Suite
 - Browser: Firefox
 - Version: 12

**Additional context**
Generated trace back. See below

**Relevant logs (please use a tool like `fpaste` or a service like pastebin.)**
The settings of extension screen-rotate@shyzus.github.io had an error:
```
SyntaxError: import declarations may only appear at top level of a module
```

Stack trace:
```
@file:///usr/share/gnome-shell/extensions/screen-rotate@shyzus.github.io/prefs.js:22:24
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

**Comment by shyzus** [comment]
@luyatshimbalanga Thanks for this issue. This is expected to fail under GNOME 45 due to a massive overhaul of how extensions are loaded with GNOME 45. To close this issue. The extension will have to be ported to GNOME 45 see this [link](https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm)

**Comment by yfreund** [comment]
I tested the branch on Ubuntu 23.10 with GNOME 45rc, and it worked as expected. The mouse cursor disappeared on rotation, but came back at the correct location once I moved it - not a big deal for me personally.

Thank you for your work on this awesome extension. I can't imagine using GNOME on my Lenovo Yoga 13 without it. 😄

**Comment by luyatshimbalanga** [comment]
> @luyatshimbalanga could you please try out this branch on your system and see if it works as expected or has the same issue im experiencing?
> 
> Please use the git approach to install:
> 
> ```shell
> git clone -b 20-extension-failed-on-gnome-shell-45 https://github.com/shyzus/gnome-shell-extension-screen-autorotate.git
> cd gnome-shell-extension-screen-autorotate
> cp -r screen-rotate@shyzus.github.io ~/.local/share/gnome-shell/extensions
> ```

I confirm the extension works as intended tested on Fedora Linux 39 Design Suite prerelease running on Dell Inspiron 14 7425 2-in-1. I experienced the same cursor issue on Workstation prerelease suggesting the problem may be related to mutter. It is minor as the cursor gets visible again with a motion.

![image](https://github.com/shyzus/gnome-shell-extension-screen-autorotate/assets/7230131/3e14720a-23b0-439f-b636-6223852e7366)
