### ISSUE TITLE
RFE: change versioning convention to that used by gnome

### ISSUE THREAD

**Issue by kloczek** [shyzus/gnome-shell-extension-screen-autorotate#21]
Just has been tagged `pre-45`.
This versioning convention is hard to handle on packaging.
Is it possible to that one which is used by GNOME? 🤔 
https://discourse.gnome.org/t/new-gnome-versioning-scheme/4235
So in this case it would be better to tag that as `45.aplha` (and git tag like `v45.alpha`) or so.

**Comment by shyzus** [comment]
Well there a few reasons why the extension’s own version is not tied directly to gnome versions.

but with the tag pre-45 it is not only reflected to 45.alpha. That tag has support for all gnome versions from gnome 40 to gnome 44.

All the other tags have a specific number attached to them that matches the version number generated by https://extensions.gnome.org 

Such as 13. If the naming of this specific tag is an issue what I can try to do is rename this specific one to something like ‘40_44’ or continue with the version numbering as before making it tagged as ‘v13’.

Please let me know what you think of this @kloczek

**Comment by kloczek** [comment]
If you've been thinking about tag next version as `v13` I suggest use `v13.0` as final tag and tag `pre-45` as `v13.alpha`

**Comment by shyzus** [comment]
Ah okay. I think what il do is change ‘pre-45’ to ‘v13’ as that is the version extensions.gnome.org will generate.

Thank you for your comments.

**Comment by kloczek** [comment]
Thank you 👍 😄
