### ISSUE TITLE
Flip in tablet mode

### ISSUE THREAD

**Issue by ttoommxx** [shyzus/gnome-shell-extension-screen-autorotate#29]
**Is your feature request related to a problem? Please describe.**
I have a convertible laptop. When I write in it everything is fine and don't need to flip the laptop. When I convert it to tent mode, the auto-rotation enables automatically and so if flips. However, if I return it to normal mode, the auto-rotation disables and the screen stays in the inverted position. Clearly I could flip it around before converting it and the auto-rotation would kick in correctly, but factually I often forget about it.

**Describe the solution you'd like**
I would like my device to rotate the screen (flip landscape) automatically when tablet mode is on, and restore it to normal position when tablet mode is off.

**Describe alternatives you've considered**
This could be implemented with a toggle in the settings of the extension.

**Additional context**
N/A

**Comment by shyzus** [comment]
Hi @ttoommxx, I have read your issue.

I have a concern which is making this work off of `tablet-mode` as you call it is not particularly reliable or easy to detect in a lot of cases. The correct way is for the kernel to push an event when a supported device enters/leaves tablet mode. but this only works with supported devices.

Sadly there are a lot of unsupported devices where the kernel does not push any event regarding tablet mode. In which case it becomes pretty difficult to detect reliably.

Perhaps a better solution would be to utilize this setting: 
![image](https://github.com/shyzus/gnome-shell-extension-screen-autorotate/assets/12612358/627f0e57-fc56-4abc-a1ec-5d5bc4968302)

This should give you a quicktoggle allowing you to rotate the screen to whatever orientation you want, without physically rotating it.
![image](https://github.com/shyzus/gnome-shell-extension-screen-autorotate/assets/12612358/38bdf01a-b0dc-4670-84d2-1c4043b29139)

Also double tapping the rotate quicktoggle should set your orientation to landscape as well. That way you don't need to open the quicktoggle menu

**Comment by ttoommxx** [comment]
Sure thing, that's exactly what I did for now. Thank you for the suggestion, and thank you for setting up this awesome extension :)

**Comment by shyzus** [comment]
I will be closing this issue as resolved then have a good day.
