### ISSUE TITLE
Lenovo IdePpad Yoga 13 autorotate not working

### ISSUE THREAD

**Issue by saddy123** [shyzus/gnome-shell-extension-screen-autorotate#8]
**Describe the bug**

**To Reproduce**
1. Go to 'user menu in the upper right, activate the autorotate'
2. Flip Display / Keyboard
3. Rotate the screen
4. Nothing happens

**Expected behavior**
rotating screen

**Desktop (please complete the following information):**
 - 1 week old manjaro gnomw installation, running X11 session because of shadow.tech wayland incompatibility

**Additional context**
A quick google search says that it has sensors / autorotate is working with windows

**Relevant logs (please use a tool like `fpaste` or a service like pastebin.)**
idk which ones or how to debug this

Obligatory thanks for the fork and your voluntary work!
Would really appreciate a working autorotate.

**Comment by shyzus** [comment]
Can you confirm whether [this package](https://pkgs.org/search/?q=iio-sensor-proxy) is installed? It is a dependency for this extension to work properly. You should also be able to use `journalctl -b | grep gnome-shell` to find any logs related to the gnome shell which would include of this extension.

**Comment by darrell-k** [comment]
@saddy123 , once you have confirmed that iio-sensor-proxy is installed on your system, check if it is running:
`sudo systemctl status iio-sensor-proxy`
Is it running? if not, try
`sudo systemctl start iio-sensor-proxy`
Now run the status command again - has it immediately stopped?

If it has, you might be experiencing the same problem as me (on a different but maybe similar Lenovo convertable) - the Linux kernel does not recognise the sensor hardware. I'm working on a fix with the kernel maintainers at present. If this is the case, I can help you identify your sensor hardware and if it is a similar issue, we can hopefully make sure that the fix currently in progress fixes your device too.

**Comment by DallinatorX** [comment]
I am using a Dell Inspiron 7405 and I am experiencing the same issue that you are explaining. 

After running `sudo systemctl start iio-sensor-proxy`, and then `sudo systemctl status iio-sensor-proxy`
I get:
```
Mar 09 12:39:01 Inspiron-7405-2n1 systemd[1]: Starting IIO Sensor Proxy service...
Mar 09 12:39:01 Inspiron-7405-2n1 systemd[1]: Started IIO Sensor Proxy service.
Mar 09 12:39:01 Inspiron-7405-2n1 systemd[1]: iio-sensor-proxy.service: Deactivated successfully.
```

**Comment by shyzus** [comment]
Closing this issue as it has gone stale.
