### ISSUE TITLE
inverted screen orientation

### ISSUE THREAD

**Issue by andersonlbm** [shyzus/gnome-shell-extension-screen-autorotate#9]
Hi, I bought a laptop with a touch screen recently. I tested the automatic rotation of the screen in several distros (manjaro, deepin, fedora, ubuntu...) in all cases the screen is inverted in any direction. In this extension there is a function to invert the screen orientation, but this corrects the orientation only when the screen is vertical. basically my problem is that the horizontal screen keeps inverted both with the option to invert the screen on and off

i´m using fedora 37
my laptop is a kuu flexones

**Comment by shyzus** [comment]
@andersonlbm Thank you for making this issue, it is appreciated.

I believe the changes in the pull request #10  will help you with your problem.

Please try out this solution by removing the extension first and the reinstalling it using the "git" method with a specific branch :
```
git clone -b 9-inverted-screen-orientation https://github.com/shyzus/gnome-shell-extension-screen-autorotate.git
cd gnome-shell-extension-screen-autorotate
cp -r screen-rotate@shyzus.github.io ~/.local/share/gnome-shell/extensions
```
Once you are able to test it please provide feedback whether this resolves your problem or not.

**Comment by andersonlbm** [comment]
thanks bro! this solved my problem <3

**Comment by shyzus** [comment]
Il be merging this shortly and pushing a new version to gnome.extensions.org. Thank you for your time and help.
